import styles from './Privacy.module.scss';

function Privacy() {
    return (
        <div className={styles.container}>
            <h3 className={styles.title}>Privacy Policy</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis aspernatur, alias doloribus, in quasi quae mollitia impedit porro eligendi accusamus, ipsa consequuntur. Voluptatibus esse doloremque ratione voluptatem blanditiis recusandae iusto dignissimos fugiat. Rem perferendis voluptatum nihil necessitatibus aperiam voluptatem aliquam dignissimos rerum mollitia alias, laborum, hic tenetur obcaecati eveniet blanditiis repudiandae quia? Ad, consequatur distinctio? Maiores nemo enim saepe, porro sunt non obcaecati at dignissimos quidem unde explicabo fuga quod cupiditate ex sequi aliquam eos dolorum, totam cumque dicta, veniam incidunt. Corrupti tempora architecto, harum impedit consequuntur praesentium delectus ad eligendi veritatis voluptates, ex veniam iure deleniti modi nam vitae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis aspernatur, alias doloribus, in quasi quae mollitia impedit porro eligendi accusamus, ipsa consequuntur. Voluptatibus esse doloremque ratione voluptatem blanditiis recusandae iusto dignissimos fugiat. Rem perferendis voluptatum nihil necessitatibus aperiam voluptatem aliquam dignissimos rerum mollitia alias, laborum, hic tenetur obcaecati eveniet blanditiis repudiandae quia? Ad, consequatur distinctio? Maiores nemo enim saepe, porro sunt non obcaecati at dignissimos quidem unde explicabo fuga quod cupiditate ex sequi aliquam eos dolorum, totam cumque dicta, veniam incidunt. Corrupti tempora architecto, harum impedit consequuntur praesentium delectus ad eligendi veritatis voluptates, ex veniam iure deleniti modi nam vitae.</p>
            <br/>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis aspernatur, alias doloribus, in quasi quae mollitia impedit porro eligendi accusamus, ipsa consequuntur. Voluptatibus esse doloremque ratione voluptatem blanditiis recusandae iusto dignissimos fugiat. Rem perferendis voluptatum nihil necessitatibus aperiam voluptatem aliquam dignissimos rerum mollitia alias, laborum, hic tenetur obcaecati eveniet blanditiis repudiandae quia? Ad, consequatur distinctio? Maiores nemo enim saepe, porro sunt non obcaecati at dignissimos quidem unde explicabo fuga quod cupiditate ex sequi aliquam eos dolorum, totam cumque dicta, veniam incidunt. Corrupti tempora architecto, harum impedit consequuntur praesentium delectus ad eligendi veritatis voluptates, ex veniam iure deleniti modi nam vitae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis aspernatur, alias doloribus, in quasi quae mollitia impedit porro eligendi accusamus, ipsa consequuntur. Voluptatibus esse doloremque ratione voluptatem blanditiis recusandae iusto dignissimos fugiat. Rem perferendis voluptatum nihil necessitatibus aperiam voluptatem aliquam dignissimos rerum mollitia alias, laborum, hic tenetur obcaecati eveniet blanditiis repudiandae quia? Ad, consequatur distinctio? Maiores nemo enim saepe, porro sunt non obcaecati at dignissimos quidem unde explicabo fuga quod cupiditate ex sequi aliquam eos dolorum, totam cumque dicta, veniam incidunt. Corrupti tempora architecto, harum impedit consequuntur praesentium delectus ad eligendi veritatis voluptates, ex veniam iure deleniti modi nam vitae.</p>
            <br/>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis aspernatur, alias doloribus, in quasi quae mollitia impedit porro eligendi accusamus, ipsa consequuntur. Voluptatibus esse doloremque ratione voluptatem blanditiis recusandae iusto dignissimos fugiat. Rem perferendis voluptatum nihil necessitatibus aperiam voluptatem aliquam dignissimos rerum mollitia alias, laborum, hic tenetur obcaecati eveniet blanditiis repudiandae quia? Ad, consequatur distinctio? Maiores nemo enim saepe, porro sunt non obcaecati at dignissimos quidem unde explicabo fuga quod cupiditate ex sequi aliquam eos dolorum, totam cumque dicta, veniam incidunt. Corrupti tempora architecto, harum impedit consequuntur praesentium delectus ad eligendi veritatis voluptates, ex veniam iure deleniti modi nam vitae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis aspernatur, alias doloribus, in quasi quae mollitia impedit porro eligendi accusamus, ipsa consequuntur. Voluptatibus esse doloremque ratione voluptatem blanditiis recusandae iusto dignissimos fugiat. Rem perferendis voluptatum nihil necessitatibus aperiam voluptatem aliquam dignissimos rerum mollitia alias, laborum, hic tenetur obcaecati eveniet blanditiis repudiandae quia? Ad, consequatur distinctio? Maiores nemo enim saepe, porro sunt non obcaecati at dignissimos quidem unde explicabo fuga quod cupiditate ex sequi aliquam eos dolorum, totam cumque dicta, veniam incidunt. Corrupti tempora architecto, harum impedit consequuntur praesentium delectus ad eligendi veritatis voluptates, ex veniam iure deleniti modi nam vitae.</p>
        </div>
    )
}

export default Privacy;